### Sign Up
POST http://localhost:3000/api/auth/signup HTTP/1.1
content-type: application/json

{
  "first_name": "John",
  "last_name": "Doe",
  "email": "",
  "birthdate": "05/31/2003",
  "password": "P@ssword123"
}

### Sign In
POST http://localhost:3000/api/auth/signin HTTP/1.1
content-type: application/json

{
  "email": "",
  "password": "Password!23"
}

### Confirm Account
POST http://localhost:3000/api/auth/confirm-account HTTP/1.1
content-type: application/json

{
  "email": "",
  "confirmation_code": "277628"
}

### Refresh Session
POST http://localhost:3000/api/auth/refresh HTTP/1.1
content-type: application/json

{
  "refresh_token": ""
}

### Retrieve User
GET http://localhost:3000/api/user/a45804c8-7051-7038-a419-5707efdab978 HTTP/1.1
content-type: application/json
